twitter:
    consumer_key: ''
    consumer_secret: ''
    access_token_key: ''
    access_token_secret: ''
    twittername: ''
    twitterkeyword: 'gameunitsbot'
log:
  file: tipbot.log
rpc:
  host: localhost
  port: 1337
  user: gameunitsrpc
  pass: pass
  prefix: ''
coin:
  withdrawal_fee: 1
  min_withdraw: 5
  min_confirmations: 5
  min_tip: 10
  min_rain: 1
  short_name: ' UNITS'
  full_name: gameunits 
webadmin:
  enabled: false
  port: 8080
  users:
    unek: supersecretpassword
    admintwo: password
commands:
  help:
    pm: true
    channel: false
  tip:
    pm: true
    channel: true
  balance:
    pm: true
    channel: false
  withdraw:
    pm: true
    channel: false
  address:
    pm: true
    channel: false
  terms:
    pm: true
    channel: false
  rain:
    pm: false
    channel: true
    rain_on_last_active: 0 # amount in seconds. rain tips will fall only on users active within x seconds. leave 0 for no such behavior.
messages:
  error: 'Sorry %name%, something went wrong.'
  no_funds: "Sorry %name%, you don't have enough funds (you're %short%%short_name% short)"
  not_identified: '%name%: You need to be identified with NickServ to tip.'
  tipped: '%from% tipped %to% %amount%%short_name%! "tweet %nick% help" to claim.'
  balance: '%name% has %balance%%short_name%.'
  balance_unconfirmed: '%name% has %balance%%short_name% (unconfirmed: %unconfirmed%%short_name%)'
  deposit_address: Your deposit address %address%
  withdraw_too_small: 'Sorry %name%, you need to withdraw at least %min_withdraw%%short_name% (you have %balance%%short_name%)'
  invalid_address: 'Sorry %name%, the address you specified is invalid (%address%).'
  tip_too_small: 'Sorry %from%, your tip to %to% (%amount%%short_name%) is too small (min. %min_tip%%short_name%).'
  tip_self: "Sorry %name%, you can't tip yourself!"
  invalid_amount: 'Sorry %name%, "%amount%" is not a correct amount.'
  withdraw_success: 
    - '%name%: %amount%%short_name% has been withdrawn from your account to %address%'
    - 'You have been charged %withdrawal_fee%%short_name% withdrawal fee.'
    - 'Transaction %transaction% completed.'
  help:
    - 'You can use following commands:'
    - 'balance - displays your current wallet balance'
    - 'address - displays %full_name%  your depositaddress'
    - 'withdraw <%full_name% address> - withdraws your whole wallet balance to specified address (minus %withdrawal_fee%%short_name% withdrawal fee)'
    - 'tip <nick> <amount> - sends the specified amount of %full_name% to nickname'
    - 'terms - displays terms and conditions for using %nick%'
    - 'payout - How can I withdraw my Gameunits from tipbot ? Just Download Gameunits client from : http://gameunits.org/#downloads'
  terms:
    - 'There are no fees to use %nick%, with the exception of %withdrawal_fee%%short_name% fee on withdrawals.'
    - 'In no event shall %nick% be responsible in the event of lost, stolen or misdirected funds.'
